#pragma once
enum OBJID
{
	OBJ_ITEM,
	OBJ_PLAYER,
	OBJ_SNAKE,
	OBJ_SNAKEBODY,
	OBJ_BULLET,
	OBJ_MONSTER,
	OBJ_MONSTERCHILD,
	OBJ_BALL,
	OBJ_STICK,
	OBJ_COLLISIONKS,
	OBJ_PLAYERJINI,
	OBJ_PLAYERCHILD,
	OBJ_UI,
	OBJ_END
};

enum SCENEID { SC_MAIN, SC_JINI, SC_KMS, SC_KJE, SC_KS, SC_KSWIN, SC_KSLOSE, SC_END };
